/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CityRecord extends org.jooq.impl.UpdatableRecordImpl<gudusoft.sakila.tables.records.CityRecord> implements org.jooq.Record4<org.jooq.types.UShort, java.lang.String, org.jooq.types.UShort, java.sql.Timestamp> {

	private static final long serialVersionUID = -1340941907;

	/**
	 * Setter for <code>sakila.city.city_id</code>. 
	 */
	public void setCityId(org.jooq.types.UShort value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sakila.city.city_id</code>. 
	 */
	public org.jooq.types.UShort getCityId() {
		return (org.jooq.types.UShort) getValue(0);
	}

	/**
	 * Setter for <code>sakila.city.city</code>. 
	 */
	public void setCity(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sakila.city.city</code>. 
	 */
	public java.lang.String getCity() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>sakila.city.country_id</code>. 
	 */
	public void setCountryId(org.jooq.types.UShort value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sakila.city.country_id</code>. 
	 */
	public org.jooq.types.UShort getCountryId() {
		return (org.jooq.types.UShort) getValue(2);
	}

	/**
	 * Setter for <code>sakila.city.last_update</code>. 
	 */
	public void setLastUpdate(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sakila.city.last_update</code>. 
	 */
	public java.sql.Timestamp getLastUpdate() {
		return (java.sql.Timestamp) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.UShort> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<org.jooq.types.UShort, java.lang.String, org.jooq.types.UShort, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<org.jooq.types.UShort, java.lang.String, org.jooq.types.UShort, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UShort> field1() {
		return gudusoft.sakila.tables.City.CITY.CITY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return gudusoft.sakila.tables.City.CITY.CITY_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UShort> field3() {
		return gudusoft.sakila.tables.City.CITY.COUNTRY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return gudusoft.sakila.tables.City.CITY.LAST_UPDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UShort value1() {
		return getCityId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UShort value3() {
		return getCountryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getLastUpdate();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CityRecord
	 */
	public CityRecord() {
		super(gudusoft.sakila.tables.City.CITY);
	}
}
