/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * VIEW
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerListRecord extends org.jooq.impl.TableRecordImpl<gudusoft.sakila.tables.records.CustomerListRecord> implements org.jooq.Record9<org.jooq.types.UShort, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, org.jooq.types.UByte> {

	private static final long serialVersionUID = 657086141;

	/**
	 * Setter for <code>sakila.customer_list.ID</code>. 
	 */
	public void setId(org.jooq.types.UShort value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sakila.customer_list.ID</code>. 
	 */
	public org.jooq.types.UShort getId() {
		return (org.jooq.types.UShort) getValue(0);
	}

	/**
	 * Setter for <code>sakila.customer_list.name</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sakila.customer_list.name</code>. 
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>sakila.customer_list.address</code>. 
	 */
	public void setAddress(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sakila.customer_list.address</code>. 
	 */
	public java.lang.String getAddress() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>sakila.customer_list.zip code</code>. 
	 */
	public void setZip_code(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sakila.customer_list.zip code</code>. 
	 */
	public java.lang.String getZip_code() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>sakila.customer_list.phone</code>. 
	 */
	public void setPhone(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>sakila.customer_list.phone</code>. 
	 */
	public java.lang.String getPhone() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>sakila.customer_list.city</code>. 
	 */
	public void setCity(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>sakila.customer_list.city</code>. 
	 */
	public java.lang.String getCity() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>sakila.customer_list.country</code>. 
	 */
	public void setCountry(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>sakila.customer_list.country</code>. 
	 */
	public java.lang.String getCountry() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>sakila.customer_list.notes</code>. 
	 */
	public void setNotes(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>sakila.customer_list.notes</code>. 
	 */
	public java.lang.String getNotes() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>sakila.customer_list.SID</code>. 
	 */
	public void setSid(org.jooq.types.UByte value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>sakila.customer_list.SID</code>. 
	 */
	public org.jooq.types.UByte getSid() {
		return (org.jooq.types.UByte) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<org.jooq.types.UShort, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, org.jooq.types.UByte> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<org.jooq.types.UShort, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, org.jooq.types.UByte> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UShort> field1() {
		return gudusoft.sakila.tables.CustomerList.CUSTOMER_LIST.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return gudusoft.sakila.tables.CustomerList.CUSTOMER_LIST.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return gudusoft.sakila.tables.CustomerList.CUSTOMER_LIST.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return gudusoft.sakila.tables.CustomerList.CUSTOMER_LIST.ZIP_CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return gudusoft.sakila.tables.CustomerList.CUSTOMER_LIST.PHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return gudusoft.sakila.tables.CustomerList.CUSTOMER_LIST.CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return gudusoft.sakila.tables.CustomerList.CUSTOMER_LIST.COUNTRY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return gudusoft.sakila.tables.CustomerList.CUSTOMER_LIST.NOTES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field9() {
		return gudusoft.sakila.tables.CustomerList.CUSTOMER_LIST.SID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UShort value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getZip_code();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getPhone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getCountry();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getNotes();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value9() {
		return getSid();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CustomerListRecord
	 */
	public CustomerListRecord() {
		super(gudusoft.sakila.tables.CustomerList.CUSTOMER_LIST);
	}
}
