/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmRecord extends org.jooq.impl.UpdatableRecordImpl<gudusoft.sakila.tables.records.FilmRecord> implements org.jooq.Record13<org.jooq.types.UShort, java.lang.String, java.lang.String, java.lang.String, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, java.math.BigDecimal, org.jooq.types.UShort, java.math.BigDecimal, gudusoft.sakila.enums.FilmRating, java.lang.String, java.sql.Timestamp> {

	private static final long serialVersionUID = -23707518;

	/**
	 * Setter for <code>sakila.film.film_id</code>. 
	 */
	public void setFilmId(org.jooq.types.UShort value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sakila.film.film_id</code>. 
	 */
	public org.jooq.types.UShort getFilmId() {
		return (org.jooq.types.UShort) getValue(0);
	}

	/**
	 * Setter for <code>sakila.film.title</code>. 
	 */
	public void setTitle(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sakila.film.title</code>. 
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>sakila.film.description</code>. 
	 */
	public void setDescription(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sakila.film.description</code>. 
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>sakila.film.release_year</code>. 
	 */
	public void setReleaseYear(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sakila.film.release_year</code>. 
	 */
	public java.lang.String getReleaseYear() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>sakila.film.language_id</code>. 
	 */
	public void setLanguageId(org.jooq.types.UByte value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>sakila.film.language_id</code>. 
	 */
	public org.jooq.types.UByte getLanguageId() {
		return (org.jooq.types.UByte) getValue(4);
	}

	/**
	 * Setter for <code>sakila.film.original_language_id</code>. 
	 */
	public void setOriginalLanguageId(org.jooq.types.UByte value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>sakila.film.original_language_id</code>. 
	 */
	public org.jooq.types.UByte getOriginalLanguageId() {
		return (org.jooq.types.UByte) getValue(5);
	}

	/**
	 * Setter for <code>sakila.film.rental_duration</code>. 
	 */
	public void setRentalDuration(org.jooq.types.UByte value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>sakila.film.rental_duration</code>. 
	 */
	public org.jooq.types.UByte getRentalDuration() {
		return (org.jooq.types.UByte) getValue(6);
	}

	/**
	 * Setter for <code>sakila.film.rental_rate</code>. 
	 */
	public void setRentalRate(java.math.BigDecimal value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>sakila.film.rental_rate</code>. 
	 */
	public java.math.BigDecimal getRentalRate() {
		return (java.math.BigDecimal) getValue(7);
	}

	/**
	 * Setter for <code>sakila.film.length</code>. 
	 */
	public void setLength(org.jooq.types.UShort value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>sakila.film.length</code>. 
	 */
	public org.jooq.types.UShort getLength() {
		return (org.jooq.types.UShort) getValue(8);
	}

	/**
	 * Setter for <code>sakila.film.replacement_cost</code>. 
	 */
	public void setReplacementCost(java.math.BigDecimal value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>sakila.film.replacement_cost</code>. 
	 */
	public java.math.BigDecimal getReplacementCost() {
		return (java.math.BigDecimal) getValue(9);
	}

	/**
	 * Setter for <code>sakila.film.rating</code>. 
	 */
	public void setRating(gudusoft.sakila.enums.FilmRating value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>sakila.film.rating</code>. 
	 */
	public gudusoft.sakila.enums.FilmRating getRating() {
		return (gudusoft.sakila.enums.FilmRating) getValue(10);
	}

	/**
	 * Setter for <code>sakila.film.special_features</code>. 
	 */
	public void setSpecialFeatures(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>sakila.film.special_features</code>. 
	 */
	public java.lang.String getSpecialFeatures() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>sakila.film.last_update</code>. 
	 */
	public void setLastUpdate(java.sql.Timestamp value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>sakila.film.last_update</code>. 
	 */
	public java.sql.Timestamp getLastUpdate() {
		return (java.sql.Timestamp) getValue(12);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.UShort> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record13 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row13<org.jooq.types.UShort, java.lang.String, java.lang.String, java.lang.String, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, java.math.BigDecimal, org.jooq.types.UShort, java.math.BigDecimal, gudusoft.sakila.enums.FilmRating, java.lang.String, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row13) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row13<org.jooq.types.UShort, java.lang.String, java.lang.String, java.lang.String, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, java.math.BigDecimal, org.jooq.types.UShort, java.math.BigDecimal, gudusoft.sakila.enums.FilmRating, java.lang.String, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row13) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UShort> field1() {
		return gudusoft.sakila.tables.Film.FILM.FILM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return gudusoft.sakila.tables.Film.FILM.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return gudusoft.sakila.tables.Film.FILM.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return gudusoft.sakila.tables.Film.FILM.RELEASE_YEAR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field5() {
		return gudusoft.sakila.tables.Film.FILM.LANGUAGE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field6() {
		return gudusoft.sakila.tables.Film.FILM.ORIGINAL_LANGUAGE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field7() {
		return gudusoft.sakila.tables.Film.FILM.RENTAL_DURATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field8() {
		return gudusoft.sakila.tables.Film.FILM.RENTAL_RATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UShort> field9() {
		return gudusoft.sakila.tables.Film.FILM.LENGTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field10() {
		return gudusoft.sakila.tables.Film.FILM.REPLACEMENT_COST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<gudusoft.sakila.enums.FilmRating> field11() {
		return gudusoft.sakila.tables.Film.FILM.RATING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return gudusoft.sakila.tables.Film.FILM.SPECIAL_FEATURES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field13() {
		return gudusoft.sakila.tables.Film.FILM.LAST_UPDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UShort value1() {
		return getFilmId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getReleaseYear();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value5() {
		return getLanguageId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value6() {
		return getOriginalLanguageId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value7() {
		return getRentalDuration();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value8() {
		return getRentalRate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UShort value9() {
		return getLength();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value10() {
		return getReplacementCost();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public gudusoft.sakila.enums.FilmRating value11() {
		return getRating();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getSpecialFeatures();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value13() {
		return getLastUpdate();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FilmRecord
	 */
	public FilmRecord() {
		super(gudusoft.sakila.tables.Film.FILM);
	}
}
