/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InventoryRecord extends org.jooq.impl.UpdatableRecordImpl<gudusoft.sakila.tables.records.InventoryRecord> implements org.jooq.Record4<org.jooq.types.UInteger, org.jooq.types.UShort, org.jooq.types.UByte, java.sql.Timestamp> {

	private static final long serialVersionUID = -320320149;

	/**
	 * Setter for <code>sakila.inventory.inventory_id</code>. 
	 */
	public void setInventoryId(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sakila.inventory.inventory_id</code>. 
	 */
	public org.jooq.types.UInteger getInventoryId() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>sakila.inventory.film_id</code>. 
	 */
	public void setFilmId(org.jooq.types.UShort value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sakila.inventory.film_id</code>. 
	 */
	public org.jooq.types.UShort getFilmId() {
		return (org.jooq.types.UShort) getValue(1);
	}

	/**
	 * Setter for <code>sakila.inventory.store_id</code>. 
	 */
	public void setStoreId(org.jooq.types.UByte value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sakila.inventory.store_id</code>. 
	 */
	public org.jooq.types.UByte getStoreId() {
		return (org.jooq.types.UByte) getValue(2);
	}

	/**
	 * Setter for <code>sakila.inventory.last_update</code>. 
	 */
	public void setLastUpdate(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sakila.inventory.last_update</code>. 
	 */
	public java.sql.Timestamp getLastUpdate() {
		return (java.sql.Timestamp) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.UInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<org.jooq.types.UInteger, org.jooq.types.UShort, org.jooq.types.UByte, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<org.jooq.types.UInteger, org.jooq.types.UShort, org.jooq.types.UByte, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return gudusoft.sakila.tables.Inventory.INVENTORY.INVENTORY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UShort> field2() {
		return gudusoft.sakila.tables.Inventory.INVENTORY.FILM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field3() {
		return gudusoft.sakila.tables.Inventory.INVENTORY.STORE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return gudusoft.sakila.tables.Inventory.INVENTORY.LAST_UPDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getInventoryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UShort value2() {
		return getFilmId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value3() {
		return getStoreId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getLastUpdate();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached InventoryRecord
	 */
	public InventoryRecord() {
		super(gudusoft.sakila.tables.Inventory.INVENTORY);
	}
}
