/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * VIEW
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NicerButSlowerFilmListRecord extends org.jooq.impl.TableRecordImpl<gudusoft.sakila.tables.records.NicerButSlowerFilmListRecord> implements org.jooq.Record8<org.jooq.types.UShort, java.lang.String, java.lang.String, java.lang.String, java.math.BigDecimal, org.jooq.types.UShort, gudusoft.sakila.enums.NicerButSlowerFilmListRating, java.lang.String> {

	private static final long serialVersionUID = 1209711534;

	/**
	 * Setter for <code>sakila.nicer_but_slower_film_list.FID</code>. 
	 */
	public void setFid(org.jooq.types.UShort value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sakila.nicer_but_slower_film_list.FID</code>. 
	 */
	public org.jooq.types.UShort getFid() {
		return (org.jooq.types.UShort) getValue(0);
	}

	/**
	 * Setter for <code>sakila.nicer_but_slower_film_list.title</code>. 
	 */
	public void setTitle(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sakila.nicer_but_slower_film_list.title</code>. 
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>sakila.nicer_but_slower_film_list.description</code>. 
	 */
	public void setDescription(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sakila.nicer_but_slower_film_list.description</code>. 
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>sakila.nicer_but_slower_film_list.category</code>. 
	 */
	public void setCategory(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sakila.nicer_but_slower_film_list.category</code>. 
	 */
	public java.lang.String getCategory() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>sakila.nicer_but_slower_film_list.price</code>. 
	 */
	public void setPrice(java.math.BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>sakila.nicer_but_slower_film_list.price</code>. 
	 */
	public java.math.BigDecimal getPrice() {
		return (java.math.BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>sakila.nicer_but_slower_film_list.length</code>. 
	 */
	public void setLength(org.jooq.types.UShort value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>sakila.nicer_but_slower_film_list.length</code>. 
	 */
	public org.jooq.types.UShort getLength() {
		return (org.jooq.types.UShort) getValue(5);
	}

	/**
	 * Setter for <code>sakila.nicer_but_slower_film_list.rating</code>. 
	 */
	public void setRating(gudusoft.sakila.enums.NicerButSlowerFilmListRating value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>sakila.nicer_but_slower_film_list.rating</code>. 
	 */
	public gudusoft.sakila.enums.NicerButSlowerFilmListRating getRating() {
		return (gudusoft.sakila.enums.NicerButSlowerFilmListRating) getValue(6);
	}

	/**
	 * Setter for <code>sakila.nicer_but_slower_film_list.actors</code>. 
	 */
	public void setActors(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>sakila.nicer_but_slower_film_list.actors</code>. 
	 */
	public java.lang.String getActors() {
		return (java.lang.String) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<org.jooq.types.UShort, java.lang.String, java.lang.String, java.lang.String, java.math.BigDecimal, org.jooq.types.UShort, gudusoft.sakila.enums.NicerButSlowerFilmListRating, java.lang.String> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<org.jooq.types.UShort, java.lang.String, java.lang.String, java.lang.String, java.math.BigDecimal, org.jooq.types.UShort, gudusoft.sakila.enums.NicerButSlowerFilmListRating, java.lang.String> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UShort> field1() {
		return gudusoft.sakila.tables.NicerButSlowerFilmList.NICER_BUT_SLOWER_FILM_LIST.FID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return gudusoft.sakila.tables.NicerButSlowerFilmList.NICER_BUT_SLOWER_FILM_LIST.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return gudusoft.sakila.tables.NicerButSlowerFilmList.NICER_BUT_SLOWER_FILM_LIST.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return gudusoft.sakila.tables.NicerButSlowerFilmList.NICER_BUT_SLOWER_FILM_LIST.CATEGORY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field5() {
		return gudusoft.sakila.tables.NicerButSlowerFilmList.NICER_BUT_SLOWER_FILM_LIST.PRICE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UShort> field6() {
		return gudusoft.sakila.tables.NicerButSlowerFilmList.NICER_BUT_SLOWER_FILM_LIST.LENGTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<gudusoft.sakila.enums.NicerButSlowerFilmListRating> field7() {
		return gudusoft.sakila.tables.NicerButSlowerFilmList.NICER_BUT_SLOWER_FILM_LIST.RATING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return gudusoft.sakila.tables.NicerButSlowerFilmList.NICER_BUT_SLOWER_FILM_LIST.ACTORS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UShort value1() {
		return getFid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getCategory();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value5() {
		return getPrice();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UShort value6() {
		return getLength();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public gudusoft.sakila.enums.NicerButSlowerFilmListRating value7() {
		return getRating();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getActors();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached NicerButSlowerFilmListRecord
	 */
	public NicerButSlowerFilmListRecord() {
		super(gudusoft.sakila.tables.NicerButSlowerFilmList.NICER_BUT_SLOWER_FILM_LIST);
	}
}
