/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RentalRecord extends org.jooq.impl.UpdatableRecordImpl<gudusoft.sakila.tables.records.RentalRecord> implements org.jooq.Record7<java.lang.Integer, java.sql.Timestamp, org.jooq.types.UInteger, org.jooq.types.UShort, java.sql.Timestamp, org.jooq.types.UByte, java.sql.Timestamp> {

	private static final long serialVersionUID = 862915388;

	/**
	 * Setter for <code>sakila.rental.rental_id</code>. 
	 */
	public void setRentalId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sakila.rental.rental_id</code>. 
	 */
	public java.lang.Integer getRentalId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>sakila.rental.rental_date</code>. 
	 */
	public void setRentalDate(java.sql.Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sakila.rental.rental_date</code>. 
	 */
	public java.sql.Timestamp getRentalDate() {
		return (java.sql.Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>sakila.rental.inventory_id</code>. 
	 */
	public void setInventoryId(org.jooq.types.UInteger value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sakila.rental.inventory_id</code>. 
	 */
	public org.jooq.types.UInteger getInventoryId() {
		return (org.jooq.types.UInteger) getValue(2);
	}

	/**
	 * Setter for <code>sakila.rental.customer_id</code>. 
	 */
	public void setCustomerId(org.jooq.types.UShort value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sakila.rental.customer_id</code>. 
	 */
	public org.jooq.types.UShort getCustomerId() {
		return (org.jooq.types.UShort) getValue(3);
	}

	/**
	 * Setter for <code>sakila.rental.return_date</code>. 
	 */
	public void setReturnDate(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>sakila.rental.return_date</code>. 
	 */
	public java.sql.Timestamp getReturnDate() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>sakila.rental.staff_id</code>. 
	 */
	public void setStaffId(org.jooq.types.UByte value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>sakila.rental.staff_id</code>. 
	 */
	public org.jooq.types.UByte getStaffId() {
		return (org.jooq.types.UByte) getValue(5);
	}

	/**
	 * Setter for <code>sakila.rental.last_update</code>. 
	 */
	public void setLastUpdate(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>sakila.rental.last_update</code>. 
	 */
	public java.sql.Timestamp getLastUpdate() {
		return (java.sql.Timestamp) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.sql.Timestamp, org.jooq.types.UInteger, org.jooq.types.UShort, java.sql.Timestamp, org.jooq.types.UByte, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.sql.Timestamp, org.jooq.types.UInteger, org.jooq.types.UShort, java.sql.Timestamp, org.jooq.types.UByte, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return gudusoft.sakila.tables.Rental.RENTAL.RENTAL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field2() {
		return gudusoft.sakila.tables.Rental.RENTAL.RENTAL_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field3() {
		return gudusoft.sakila.tables.Rental.RENTAL.INVENTORY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UShort> field4() {
		return gudusoft.sakila.tables.Rental.RENTAL.CUSTOMER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return gudusoft.sakila.tables.Rental.RENTAL.RETURN_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field6() {
		return gudusoft.sakila.tables.Rental.RENTAL.STAFF_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return gudusoft.sakila.tables.Rental.RENTAL.LAST_UPDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getRentalId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value2() {
		return getRentalDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value3() {
		return getInventoryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UShort value4() {
		return getCustomerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getReturnDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value6() {
		return getStaffId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getLastUpdate();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RentalRecord
	 */
	public RentalRecord() {
		super(gudusoft.sakila.tables.Rental.RENTAL);
	}
}
