/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila.tables;

/**
 * This class is generated by jOOQ.
 *
 * VIEW
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActorInfo extends org.jooq.impl.TableImpl<gudusoft.sakila.tables.records.ActorInfoRecord> {

	private static final long serialVersionUID = -482134379;

	/**
	 * The singleton instance of <code>sakila.actor_info</code>
	 */
	public static final gudusoft.sakila.tables.ActorInfo ACTOR_INFO = new gudusoft.sakila.tables.ActorInfo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<gudusoft.sakila.tables.records.ActorInfoRecord> getRecordType() {
		return gudusoft.sakila.tables.records.ActorInfoRecord.class;
	}

	/**
	 * The column <code>sakila.actor_info.actor_id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.ActorInfoRecord, org.jooq.types.UShort> ACTOR_ID = createField("actor_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED, this);

	/**
	 * The column <code>sakila.actor_info.first_name</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.ActorInfoRecord, java.lang.String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.length(45), this);

	/**
	 * The column <code>sakila.actor_info.last_name</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.ActorInfoRecord, java.lang.String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(45), this);

	/**
	 * The column <code>sakila.actor_info.film_info</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.ActorInfoRecord, java.lang.String> FILM_INFO = createField("film_info", org.jooq.impl.SQLDataType.CLOB.length(65535), this);

	/**
	 * Create a <code>sakila.actor_info</code> table reference
	 */
	public ActorInfo() {
		super("actor_info", gudusoft.sakila.Sakila.SAKILA);
	}

	/**
	 * Create an aliased <code>sakila.actor_info</code> table reference
	 */
	public ActorInfo(java.lang.String alias) {
		super(alias, gudusoft.sakila.Sakila.SAKILA, gudusoft.sakila.tables.ActorInfo.ACTOR_INFO);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public gudusoft.sakila.tables.ActorInfo as(java.lang.String alias) {
		return new gudusoft.sakila.tables.ActorInfo(alias);
	}
}
