/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Actor extends org.jooq.impl.TableImpl<gudusoft.sakila.tables.records.ActorRecord> {

	private static final long serialVersionUID = 2128173288;

	/**
	 * The singleton instance of <code>sakila.actor</code>
	 */
	public static final gudusoft.sakila.tables.Actor ACTOR = new gudusoft.sakila.tables.Actor();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<gudusoft.sakila.tables.records.ActorRecord> getRecordType() {
		return gudusoft.sakila.tables.records.ActorRecord.class;
	}

	/**
	 * The column <code>sakila.actor.actor_id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.ActorRecord, org.jooq.types.UShort> ACTOR_ID = createField("actor_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED, this);

	/**
	 * The column <code>sakila.actor.first_name</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.ActorRecord, java.lang.String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.length(45), this);

	/**
	 * The column <code>sakila.actor.last_name</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.ActorRecord, java.lang.String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(45), this);

	/**
	 * The column <code>sakila.actor.last_update</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.ActorRecord, java.sql.Timestamp> LAST_UPDATE = createField("last_update", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>sakila.actor</code> table reference
	 */
	public Actor() {
		super("actor", gudusoft.sakila.Sakila.SAKILA);
	}

	/**
	 * Create an aliased <code>sakila.actor</code> table reference
	 */
	public Actor(java.lang.String alias) {
		super(alias, gudusoft.sakila.Sakila.SAKILA, gudusoft.sakila.tables.Actor.ACTOR);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<gudusoft.sakila.tables.records.ActorRecord, org.jooq.types.UShort> getIdentity() {
		return gudusoft.sakila.Keys.IDENTITY_ACTOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<gudusoft.sakila.tables.records.ActorRecord> getPrimaryKey() {
		return gudusoft.sakila.Keys.KEY_ACTOR_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<gudusoft.sakila.tables.records.ActorRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<gudusoft.sakila.tables.records.ActorRecord>>asList(gudusoft.sakila.Keys.KEY_ACTOR_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public gudusoft.sakila.tables.Actor as(java.lang.String alias) {
		return new gudusoft.sakila.tables.Actor(alias);
	}
}
