/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Category extends org.jooq.impl.TableImpl<gudusoft.sakila.tables.records.CategoryRecord> {

	private static final long serialVersionUID = -1227031584;

	/**
	 * The singleton instance of <code>sakila.category</code>
	 */
	public static final gudusoft.sakila.tables.Category CATEGORY = new gudusoft.sakila.tables.Category();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<gudusoft.sakila.tables.records.CategoryRecord> getRecordType() {
		return gudusoft.sakila.tables.records.CategoryRecord.class;
	}

	/**
	 * The column <code>sakila.category.category_id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.CategoryRecord, org.jooq.types.UByte> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.TINYINTUNSIGNED, this);

	/**
	 * The column <code>sakila.category.name</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.CategoryRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(25), this);

	/**
	 * The column <code>sakila.category.last_update</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.CategoryRecord, java.sql.Timestamp> LAST_UPDATE = createField("last_update", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>sakila.category</code> table reference
	 */
	public Category() {
		super("category", gudusoft.sakila.Sakila.SAKILA);
	}

	/**
	 * Create an aliased <code>sakila.category</code> table reference
	 */
	public Category(java.lang.String alias) {
		super(alias, gudusoft.sakila.Sakila.SAKILA, gudusoft.sakila.tables.Category.CATEGORY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<gudusoft.sakila.tables.records.CategoryRecord, org.jooq.types.UByte> getIdentity() {
		return gudusoft.sakila.Keys.IDENTITY_CATEGORY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<gudusoft.sakila.tables.records.CategoryRecord> getPrimaryKey() {
		return gudusoft.sakila.Keys.KEY_CATEGORY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<gudusoft.sakila.tables.records.CategoryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<gudusoft.sakila.tables.records.CategoryRecord>>asList(gudusoft.sakila.Keys.KEY_CATEGORY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public gudusoft.sakila.tables.Category as(java.lang.String alias) {
		return new gudusoft.sakila.tables.Category(alias);
	}
}
