/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class City extends org.jooq.impl.TableImpl<gudusoft.sakila.tables.records.CityRecord> {

	private static final long serialVersionUID = -1931827119;

	/**
	 * The singleton instance of <code>sakila.city</code>
	 */
	public static final gudusoft.sakila.tables.City CITY = new gudusoft.sakila.tables.City();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<gudusoft.sakila.tables.records.CityRecord> getRecordType() {
		return gudusoft.sakila.tables.records.CityRecord.class;
	}

	/**
	 * The column <code>sakila.city.city_id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.CityRecord, org.jooq.types.UShort> CITY_ID = createField("city_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED, this);

	/**
	 * The column <code>sakila.city.city</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.CityRecord, java.lang.String> CITY_ = createField("city", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>sakila.city.country_id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.CityRecord, org.jooq.types.UShort> COUNTRY_ID = createField("country_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED, this);

	/**
	 * The column <code>sakila.city.last_update</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.CityRecord, java.sql.Timestamp> LAST_UPDATE = createField("last_update", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>sakila.city</code> table reference
	 */
	public City() {
		super("city", gudusoft.sakila.Sakila.SAKILA);
	}

	/**
	 * Create an aliased <code>sakila.city</code> table reference
	 */
	public City(java.lang.String alias) {
		super(alias, gudusoft.sakila.Sakila.SAKILA, gudusoft.sakila.tables.City.CITY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<gudusoft.sakila.tables.records.CityRecord, org.jooq.types.UShort> getIdentity() {
		return gudusoft.sakila.Keys.IDENTITY_CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<gudusoft.sakila.tables.records.CityRecord> getPrimaryKey() {
		return gudusoft.sakila.Keys.KEY_CITY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<gudusoft.sakila.tables.records.CityRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<gudusoft.sakila.tables.records.CityRecord>>asList(gudusoft.sakila.Keys.KEY_CITY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<gudusoft.sakila.tables.records.CityRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<gudusoft.sakila.tables.records.CityRecord, ?>>asList(gudusoft.sakila.Keys.FK_CITY_COUNTRY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public gudusoft.sakila.tables.City as(java.lang.String alias) {
		return new gudusoft.sakila.tables.City(alias);
	}
}
