/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila.tables;

/**
 * This class is generated by jOOQ.
 *
 * VIEW
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerList extends org.jooq.impl.TableImpl<gudusoft.sakila.tables.records.CustomerListRecord> {

	private static final long serialVersionUID = 1561761613;

	/**
	 * The singleton instance of <code>sakila.customer_list</code>
	 */
	public static final gudusoft.sakila.tables.CustomerList CUSTOMER_LIST = new gudusoft.sakila.tables.CustomerList();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<gudusoft.sakila.tables.records.CustomerListRecord> getRecordType() {
		return gudusoft.sakila.tables.records.CustomerListRecord.class;
	}

	/**
	 * The column <code>sakila.customer_list.ID</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.CustomerListRecord, org.jooq.types.UShort> ID = createField("ID", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED, this);

	/**
	 * The column <code>sakila.customer_list.name</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.CustomerListRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(91), this);

	/**
	 * The column <code>sakila.customer_list.address</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.CustomerListRecord, java.lang.String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>sakila.customer_list.zip code</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.CustomerListRecord, java.lang.String> ZIP_CODE = createField("zip code", org.jooq.impl.SQLDataType.VARCHAR.length(10), this);

	/**
	 * The column <code>sakila.customer_list.phone</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.CustomerListRecord, java.lang.String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR.length(20), this);

	/**
	 * The column <code>sakila.customer_list.city</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.CustomerListRecord, java.lang.String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>sakila.customer_list.country</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.CustomerListRecord, java.lang.String> COUNTRY = createField("country", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>sakila.customer_list.notes</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.CustomerListRecord, java.lang.String> NOTES = createField("notes", org.jooq.impl.SQLDataType.VARCHAR.length(6), this);

	/**
	 * The column <code>sakila.customer_list.SID</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.CustomerListRecord, org.jooq.types.UByte> SID = createField("SID", org.jooq.impl.SQLDataType.TINYINTUNSIGNED, this);

	/**
	 * Create a <code>sakila.customer_list</code> table reference
	 */
	public CustomerList() {
		super("customer_list", gudusoft.sakila.Sakila.SAKILA);
	}

	/**
	 * Create an aliased <code>sakila.customer_list</code> table reference
	 */
	public CustomerList(java.lang.String alias) {
		super(alias, gudusoft.sakila.Sakila.SAKILA, gudusoft.sakila.tables.CustomerList.CUSTOMER_LIST);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public gudusoft.sakila.tables.CustomerList as(java.lang.String alias) {
		return new gudusoft.sakila.tables.CustomerList(alias);
	}
}
