/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmActor extends org.jooq.impl.TableImpl<gudusoft.sakila.tables.records.FilmActorRecord> {

	private static final long serialVersionUID = 68856671;

	/**
	 * The singleton instance of <code>sakila.film_actor</code>
	 */
	public static final gudusoft.sakila.tables.FilmActor FILM_ACTOR = new gudusoft.sakila.tables.FilmActor();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<gudusoft.sakila.tables.records.FilmActorRecord> getRecordType() {
		return gudusoft.sakila.tables.records.FilmActorRecord.class;
	}

	/**
	 * The column <code>sakila.film_actor.actor_id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.FilmActorRecord, org.jooq.types.UShort> ACTOR_ID = createField("actor_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED, this);

	/**
	 * The column <code>sakila.film_actor.film_id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.FilmActorRecord, org.jooq.types.UShort> FILM_ID = createField("film_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED, this);

	/**
	 * The column <code>sakila.film_actor.last_update</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.FilmActorRecord, java.sql.Timestamp> LAST_UPDATE = createField("last_update", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>sakila.film_actor</code> table reference
	 */
	public FilmActor() {
		super("film_actor", gudusoft.sakila.Sakila.SAKILA);
	}

	/**
	 * Create an aliased <code>sakila.film_actor</code> table reference
	 */
	public FilmActor(java.lang.String alias) {
		super(alias, gudusoft.sakila.Sakila.SAKILA, gudusoft.sakila.tables.FilmActor.FILM_ACTOR);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<gudusoft.sakila.tables.records.FilmActorRecord> getPrimaryKey() {
		return gudusoft.sakila.Keys.KEY_FILM_ACTOR_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<gudusoft.sakila.tables.records.FilmActorRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<gudusoft.sakila.tables.records.FilmActorRecord>>asList(gudusoft.sakila.Keys.KEY_FILM_ACTOR_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<gudusoft.sakila.tables.records.FilmActorRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<gudusoft.sakila.tables.records.FilmActorRecord, ?>>asList(gudusoft.sakila.Keys.FK_FILM_ACTOR_ACTOR, gudusoft.sakila.Keys.FK_FILM_ACTOR_FILM);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public gudusoft.sakila.tables.FilmActor as(java.lang.String alias) {
		return new gudusoft.sakila.tables.FilmActor(alias);
	}
}
