/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmText extends org.jooq.impl.TableImpl<gudusoft.sakila.tables.records.FilmTextRecord> {

	private static final long serialVersionUID = 1507745767;

	/**
	 * The singleton instance of <code>sakila.film_text</code>
	 */
	public static final gudusoft.sakila.tables.FilmText FILM_TEXT = new gudusoft.sakila.tables.FilmText();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<gudusoft.sakila.tables.records.FilmTextRecord> getRecordType() {
		return gudusoft.sakila.tables.records.FilmTextRecord.class;
	}

	/**
	 * The column <code>sakila.film_text.film_id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.FilmTextRecord, java.lang.Short> FILM_ID = createField("film_id", org.jooq.impl.SQLDataType.SMALLINT, this);

	/**
	 * The column <code>sakila.film_text.title</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.FilmTextRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sakila.film_text.description</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.FilmTextRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB.length(65535), this);

	/**
	 * Create a <code>sakila.film_text</code> table reference
	 */
	public FilmText() {
		super("film_text", gudusoft.sakila.Sakila.SAKILA);
	}

	/**
	 * Create an aliased <code>sakila.film_text</code> table reference
	 */
	public FilmText(java.lang.String alias) {
		super(alias, gudusoft.sakila.Sakila.SAKILA, gudusoft.sakila.tables.FilmText.FILM_TEXT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<gudusoft.sakila.tables.records.FilmTextRecord> getPrimaryKey() {
		return gudusoft.sakila.Keys.KEY_FILM_TEXT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<gudusoft.sakila.tables.records.FilmTextRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<gudusoft.sakila.tables.records.FilmTextRecord>>asList(gudusoft.sakila.Keys.KEY_FILM_TEXT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public gudusoft.sakila.tables.FilmText as(java.lang.String alias) {
		return new gudusoft.sakila.tables.FilmText(alias);
	}
}
