/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmCategory extends org.jooq.impl.TableImpl<gudusoft.sakila.tables.records.FilmCategoryRecord> {

	private static final long serialVersionUID = 1857741180;

	/**
	 * The singleton instance of <code>sakila.film_category</code>
	 */
	public static final gudusoft.sakila.tables.FilmCategory FILM_CATEGORY = new gudusoft.sakila.tables.FilmCategory();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<gudusoft.sakila.tables.records.FilmCategoryRecord> getRecordType() {
		return gudusoft.sakila.tables.records.FilmCategoryRecord.class;
	}

	/**
	 * The column <code>sakila.film_category.film_id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.FilmCategoryRecord, org.jooq.types.UShort> FILM_ID = createField("film_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED, this);

	/**
	 * The column <code>sakila.film_category.category_id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.FilmCategoryRecord, org.jooq.types.UByte> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.TINYINTUNSIGNED, this);

	/**
	 * The column <code>sakila.film_category.last_update</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.FilmCategoryRecord, java.sql.Timestamp> LAST_UPDATE = createField("last_update", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>sakila.film_category</code> table reference
	 */
	public FilmCategory() {
		super("film_category", gudusoft.sakila.Sakila.SAKILA);
	}

	/**
	 * Create an aliased <code>sakila.film_category</code> table reference
	 */
	public FilmCategory(java.lang.String alias) {
		super(alias, gudusoft.sakila.Sakila.SAKILA, gudusoft.sakila.tables.FilmCategory.FILM_CATEGORY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<gudusoft.sakila.tables.records.FilmCategoryRecord> getPrimaryKey() {
		return gudusoft.sakila.Keys.KEY_FILM_CATEGORY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<gudusoft.sakila.tables.records.FilmCategoryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<gudusoft.sakila.tables.records.FilmCategoryRecord>>asList(gudusoft.sakila.Keys.KEY_FILM_CATEGORY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<gudusoft.sakila.tables.records.FilmCategoryRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<gudusoft.sakila.tables.records.FilmCategoryRecord, ?>>asList(gudusoft.sakila.Keys.FK_FILM_CATEGORY_FILM, gudusoft.sakila.Keys.FK_FILM_CATEGORY_CATEGORY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public gudusoft.sakila.tables.FilmCategory as(java.lang.String alias) {
		return new gudusoft.sakila.tables.FilmCategory(alias);
	}
}
