/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila.tables;

/**
 * This class is generated by jOOQ.
 *
 * VIEW
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmList extends org.jooq.impl.TableImpl<gudusoft.sakila.tables.records.FilmListRecord> {

	private static final long serialVersionUID = 209348878;

	/**
	 * The singleton instance of <code>sakila.film_list</code>
	 */
	public static final gudusoft.sakila.tables.FilmList FILM_LIST = new gudusoft.sakila.tables.FilmList();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<gudusoft.sakila.tables.records.FilmListRecord> getRecordType() {
		return gudusoft.sakila.tables.records.FilmListRecord.class;
	}

	/**
	 * The column <code>sakila.film_list.FID</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.FilmListRecord, org.jooq.types.UShort> FID = createField("FID", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED, this);

	/**
	 * The column <code>sakila.film_list.title</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.FilmListRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sakila.film_list.description</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.FilmListRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB.length(65535), this);

	/**
	 * The column <code>sakila.film_list.category</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.FilmListRecord, java.lang.String> CATEGORY = createField("category", org.jooq.impl.SQLDataType.VARCHAR.length(25), this);

	/**
	 * The column <code>sakila.film_list.price</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.FilmListRecord, java.math.BigDecimal> PRICE = createField("price", org.jooq.impl.SQLDataType.DECIMAL.precision(4, 2), this);

	/**
	 * The column <code>sakila.film_list.length</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.FilmListRecord, org.jooq.types.UShort> LENGTH = createField("length", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED, this);

	/**
	 * The column <code>sakila.film_list.rating</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.FilmListRecord, gudusoft.sakila.enums.FilmListRating> RATING = createField("rating", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(gudusoft.sakila.enums.FilmListRating.class), this);

	/**
	 * The column <code>sakila.film_list.actors</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.FilmListRecord, java.lang.String> ACTORS = createField("actors", org.jooq.impl.SQLDataType.CLOB.length(65535), this);

	/**
	 * Create a <code>sakila.film_list</code> table reference
	 */
	public FilmList() {
		super("film_list", gudusoft.sakila.Sakila.SAKILA);
	}

	/**
	 * Create an aliased <code>sakila.film_list</code> table reference
	 */
	public FilmList(java.lang.String alias) {
		super(alias, gudusoft.sakila.Sakila.SAKILA, gudusoft.sakila.tables.FilmList.FILM_LIST);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public gudusoft.sakila.tables.FilmList as(java.lang.String alias) {
		return new gudusoft.sakila.tables.FilmList(alias);
	}
}
