/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Language extends org.jooq.impl.TableImpl<gudusoft.sakila.tables.records.LanguageRecord> {

	private static final long serialVersionUID = -708774610;

	/**
	 * The singleton instance of <code>sakila.language</code>
	 */
	public static final gudusoft.sakila.tables.Language LANGUAGE = new gudusoft.sakila.tables.Language();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<gudusoft.sakila.tables.records.LanguageRecord> getRecordType() {
		return gudusoft.sakila.tables.records.LanguageRecord.class;
	}

	/**
	 * The column <code>sakila.language.language_id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.LanguageRecord, org.jooq.types.UByte> LANGUAGE_ID = createField("language_id", org.jooq.impl.SQLDataType.TINYINTUNSIGNED, this);

	/**
	 * The column <code>sakila.language.name</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.LanguageRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.CHAR.length(20), this);

	/**
	 * The column <code>sakila.language.last_update</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.LanguageRecord, java.sql.Timestamp> LAST_UPDATE = createField("last_update", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>sakila.language</code> table reference
	 */
	public Language() {
		super("language", gudusoft.sakila.Sakila.SAKILA);
	}

	/**
	 * Create an aliased <code>sakila.language</code> table reference
	 */
	public Language(java.lang.String alias) {
		super(alias, gudusoft.sakila.Sakila.SAKILA, gudusoft.sakila.tables.Language.LANGUAGE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<gudusoft.sakila.tables.records.LanguageRecord, org.jooq.types.UByte> getIdentity() {
		return gudusoft.sakila.Keys.IDENTITY_LANGUAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<gudusoft.sakila.tables.records.LanguageRecord> getPrimaryKey() {
		return gudusoft.sakila.Keys.KEY_LANGUAGE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<gudusoft.sakila.tables.records.LanguageRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<gudusoft.sakila.tables.records.LanguageRecord>>asList(gudusoft.sakila.Keys.KEY_LANGUAGE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public gudusoft.sakila.tables.Language as(java.lang.String alias) {
		return new gudusoft.sakila.tables.Language(alias);
	}
}
