/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Payment extends org.jooq.impl.TableImpl<gudusoft.sakila.tables.records.PaymentRecord> {

	private static final long serialVersionUID = -1062835986;

	/**
	 * The singleton instance of <code>sakila.payment</code>
	 */
	public static final gudusoft.sakila.tables.Payment PAYMENT = new gudusoft.sakila.tables.Payment();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<gudusoft.sakila.tables.records.PaymentRecord> getRecordType() {
		return gudusoft.sakila.tables.records.PaymentRecord.class;
	}

	/**
	 * The column <code>sakila.payment.payment_id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.PaymentRecord, org.jooq.types.UShort> PAYMENT_ID = createField("payment_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED, this);

	/**
	 * The column <code>sakila.payment.customer_id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.PaymentRecord, org.jooq.types.UShort> CUSTOMER_ID = createField("customer_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED, this);

	/**
	 * The column <code>sakila.payment.staff_id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.PaymentRecord, org.jooq.types.UByte> STAFF_ID = createField("staff_id", org.jooq.impl.SQLDataType.TINYINTUNSIGNED, this);

	/**
	 * The column <code>sakila.payment.rental_id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.PaymentRecord, java.lang.Integer> RENTAL_ID = createField("rental_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sakila.payment.amount</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.PaymentRecord, java.math.BigDecimal> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.DECIMAL.precision(5, 2), this);

	/**
	 * The column <code>sakila.payment.payment_date</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.PaymentRecord, java.sql.Timestamp> PAYMENT_DATE = createField("payment_date", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>sakila.payment.last_update</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.PaymentRecord, java.sql.Timestamp> LAST_UPDATE = createField("last_update", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>sakila.payment</code> table reference
	 */
	public Payment() {
		super("payment", gudusoft.sakila.Sakila.SAKILA);
	}

	/**
	 * Create an aliased <code>sakila.payment</code> table reference
	 */
	public Payment(java.lang.String alias) {
		super(alias, gudusoft.sakila.Sakila.SAKILA, gudusoft.sakila.tables.Payment.PAYMENT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<gudusoft.sakila.tables.records.PaymentRecord, org.jooq.types.UShort> getIdentity() {
		return gudusoft.sakila.Keys.IDENTITY_PAYMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<gudusoft.sakila.tables.records.PaymentRecord> getPrimaryKey() {
		return gudusoft.sakila.Keys.KEY_PAYMENT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<gudusoft.sakila.tables.records.PaymentRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<gudusoft.sakila.tables.records.PaymentRecord>>asList(gudusoft.sakila.Keys.KEY_PAYMENT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<gudusoft.sakila.tables.records.PaymentRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<gudusoft.sakila.tables.records.PaymentRecord, ?>>asList(gudusoft.sakila.Keys.FK_PAYMENT_CUSTOMER, gudusoft.sakila.Keys.FK_PAYMENT_STAFF, gudusoft.sakila.Keys.FK_PAYMENT_RENTAL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public gudusoft.sakila.tables.Payment as(java.lang.String alias) {
		return new gudusoft.sakila.tables.Payment(alias);
	}
}
