/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rental extends org.jooq.impl.TableImpl<gudusoft.sakila.tables.records.RentalRecord> {

	private static final long serialVersionUID = 1616295332;

	/**
	 * The singleton instance of <code>sakila.rental</code>
	 */
	public static final gudusoft.sakila.tables.Rental RENTAL = new gudusoft.sakila.tables.Rental();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<gudusoft.sakila.tables.records.RentalRecord> getRecordType() {
		return gudusoft.sakila.tables.records.RentalRecord.class;
	}

	/**
	 * The column <code>sakila.rental.rental_id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.RentalRecord, java.lang.Integer> RENTAL_ID = createField("rental_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sakila.rental.rental_date</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.RentalRecord, java.sql.Timestamp> RENTAL_DATE = createField("rental_date", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>sakila.rental.inventory_id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.RentalRecord, org.jooq.types.UInteger> INVENTORY_ID = createField("inventory_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this);

	/**
	 * The column <code>sakila.rental.customer_id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.RentalRecord, org.jooq.types.UShort> CUSTOMER_ID = createField("customer_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED, this);

	/**
	 * The column <code>sakila.rental.return_date</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.RentalRecord, java.sql.Timestamp> RETURN_DATE = createField("return_date", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>sakila.rental.staff_id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.RentalRecord, org.jooq.types.UByte> STAFF_ID = createField("staff_id", org.jooq.impl.SQLDataType.TINYINTUNSIGNED, this);

	/**
	 * The column <code>sakila.rental.last_update</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.RentalRecord, java.sql.Timestamp> LAST_UPDATE = createField("last_update", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>sakila.rental</code> table reference
	 */
	public Rental() {
		super("rental", gudusoft.sakila.Sakila.SAKILA);
	}

	/**
	 * Create an aliased <code>sakila.rental</code> table reference
	 */
	public Rental(java.lang.String alias) {
		super(alias, gudusoft.sakila.Sakila.SAKILA, gudusoft.sakila.tables.Rental.RENTAL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<gudusoft.sakila.tables.records.RentalRecord, java.lang.Integer> getIdentity() {
		return gudusoft.sakila.Keys.IDENTITY_RENTAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<gudusoft.sakila.tables.records.RentalRecord> getPrimaryKey() {
		return gudusoft.sakila.Keys.KEY_RENTAL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<gudusoft.sakila.tables.records.RentalRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<gudusoft.sakila.tables.records.RentalRecord>>asList(gudusoft.sakila.Keys.KEY_RENTAL_PRIMARY, gudusoft.sakila.Keys.KEY_RENTAL_RENTAL_DATE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<gudusoft.sakila.tables.records.RentalRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<gudusoft.sakila.tables.records.RentalRecord, ?>>asList(gudusoft.sakila.Keys.FK_RENTAL_INVENTORY, gudusoft.sakila.Keys.FK_RENTAL_CUSTOMER, gudusoft.sakila.Keys.FK_RENTAL_STAFF);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public gudusoft.sakila.tables.Rental as(java.lang.String alias) {
		return new gudusoft.sakila.tables.Rental(alias);
	}
}
