/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila.tables;

/**
 * This class is generated by jOOQ.
 *
 * VIEW
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SalesByFilmCategory extends org.jooq.impl.TableImpl<gudusoft.sakila.tables.records.SalesByFilmCategoryRecord> {

	private static final long serialVersionUID = -1760863518;

	/**
	 * The singleton instance of <code>sakila.sales_by_film_category</code>
	 */
	public static final gudusoft.sakila.tables.SalesByFilmCategory SALES_BY_FILM_CATEGORY = new gudusoft.sakila.tables.SalesByFilmCategory();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<gudusoft.sakila.tables.records.SalesByFilmCategoryRecord> getRecordType() {
		return gudusoft.sakila.tables.records.SalesByFilmCategoryRecord.class;
	}

	/**
	 * The column <code>sakila.sales_by_film_category.category</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.SalesByFilmCategoryRecord, java.lang.String> CATEGORY = createField("category", org.jooq.impl.SQLDataType.VARCHAR.length(25), this);

	/**
	 * The column <code>sakila.sales_by_film_category.total_sales</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.SalesByFilmCategoryRecord, java.math.BigDecimal> TOTAL_SALES = createField("total_sales", org.jooq.impl.SQLDataType.DECIMAL.precision(27, 2), this);

	/**
	 * Create a <code>sakila.sales_by_film_category</code> table reference
	 */
	public SalesByFilmCategory() {
		super("sales_by_film_category", gudusoft.sakila.Sakila.SAKILA);
	}

	/**
	 * Create an aliased <code>sakila.sales_by_film_category</code> table reference
	 */
	public SalesByFilmCategory(java.lang.String alias) {
		super(alias, gudusoft.sakila.Sakila.SAKILA, gudusoft.sakila.tables.SalesByFilmCategory.SALES_BY_FILM_CATEGORY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public gudusoft.sakila.tables.SalesByFilmCategory as(java.lang.String alias) {
		return new gudusoft.sakila.tables.SalesByFilmCategory(alias);
	}
}
