/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila.tables;

/**
 * This class is generated by jOOQ.
 *
 * VIEW
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SalesByStore extends org.jooq.impl.TableImpl<gudusoft.sakila.tables.records.SalesByStoreRecord> {

	private static final long serialVersionUID = 901195534;

	/**
	 * The singleton instance of <code>sakila.sales_by_store</code>
	 */
	public static final gudusoft.sakila.tables.SalesByStore SALES_BY_STORE = new gudusoft.sakila.tables.SalesByStore();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<gudusoft.sakila.tables.records.SalesByStoreRecord> getRecordType() {
		return gudusoft.sakila.tables.records.SalesByStoreRecord.class;
	}

	/**
	 * The column <code>sakila.sales_by_store.store</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.SalesByStoreRecord, java.lang.String> STORE = createField("store", org.jooq.impl.SQLDataType.VARCHAR.length(101), this);

	/**
	 * The column <code>sakila.sales_by_store.manager</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.SalesByStoreRecord, java.lang.String> MANAGER = createField("manager", org.jooq.impl.SQLDataType.VARCHAR.length(91), this);

	/**
	 * The column <code>sakila.sales_by_store.total_sales</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.SalesByStoreRecord, java.math.BigDecimal> TOTAL_SALES = createField("total_sales", org.jooq.impl.SQLDataType.DECIMAL.precision(27, 2), this);

	/**
	 * Create a <code>sakila.sales_by_store</code> table reference
	 */
	public SalesByStore() {
		super("sales_by_store", gudusoft.sakila.Sakila.SAKILA);
	}

	/**
	 * Create an aliased <code>sakila.sales_by_store</code> table reference
	 */
	public SalesByStore(java.lang.String alias) {
		super(alias, gudusoft.sakila.Sakila.SAKILA, gudusoft.sakila.tables.SalesByStore.SALES_BY_STORE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public gudusoft.sakila.tables.SalesByStore as(java.lang.String alias) {
		return new gudusoft.sakila.tables.SalesByStore(alias);
	}
}
