/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Staff extends org.jooq.impl.TableImpl<gudusoft.sakila.tables.records.StaffRecord> {

	private static final long serialVersionUID = -1331055080;

	/**
	 * The singleton instance of <code>sakila.staff</code>
	 */
	public static final gudusoft.sakila.tables.Staff STAFF = new gudusoft.sakila.tables.Staff();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<gudusoft.sakila.tables.records.StaffRecord> getRecordType() {
		return gudusoft.sakila.tables.records.StaffRecord.class;
	}

	/**
	 * The column <code>sakila.staff.staff_id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.StaffRecord, org.jooq.types.UByte> STAFF_ID = createField("staff_id", org.jooq.impl.SQLDataType.TINYINTUNSIGNED, this);

	/**
	 * The column <code>sakila.staff.first_name</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.StaffRecord, java.lang.String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.length(45), this);

	/**
	 * The column <code>sakila.staff.last_name</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.StaffRecord, java.lang.String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(45), this);

	/**
	 * The column <code>sakila.staff.address_id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.StaffRecord, org.jooq.types.UShort> ADDRESS_ID = createField("address_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED, this);

	/**
	 * The column <code>sakila.staff.picture</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.StaffRecord, byte[]> PICTURE = createField("picture", org.jooq.impl.SQLDataType.BLOB.length(65535), this);

	/**
	 * The column <code>sakila.staff.email</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.StaffRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>sakila.staff.store_id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.StaffRecord, org.jooq.types.UByte> STORE_ID = createField("store_id", org.jooq.impl.SQLDataType.TINYINTUNSIGNED, this);

	/**
	 * The column <code>sakila.staff.active</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.StaffRecord, java.lang.Byte> ACTIVE = createField("active", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The column <code>sakila.staff.username</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.StaffRecord, java.lang.String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(16), this);

	/**
	 * The column <code>sakila.staff.password</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.StaffRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(40), this);

	/**
	 * The column <code>sakila.staff.last_update</code>. 
	 */
	public final org.jooq.TableField<gudusoft.sakila.tables.records.StaffRecord, java.sql.Timestamp> LAST_UPDATE = createField("last_update", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>sakila.staff</code> table reference
	 */
	public Staff() {
		super("staff", gudusoft.sakila.Sakila.SAKILA);
	}

	/**
	 * Create an aliased <code>sakila.staff</code> table reference
	 */
	public Staff(java.lang.String alias) {
		super(alias, gudusoft.sakila.Sakila.SAKILA, gudusoft.sakila.tables.Staff.STAFF);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<gudusoft.sakila.tables.records.StaffRecord, org.jooq.types.UByte> getIdentity() {
		return gudusoft.sakila.Keys.IDENTITY_STAFF;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<gudusoft.sakila.tables.records.StaffRecord> getPrimaryKey() {
		return gudusoft.sakila.Keys.KEY_STAFF_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<gudusoft.sakila.tables.records.StaffRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<gudusoft.sakila.tables.records.StaffRecord>>asList(gudusoft.sakila.Keys.KEY_STAFF_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<gudusoft.sakila.tables.records.StaffRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<gudusoft.sakila.tables.records.StaffRecord, ?>>asList(gudusoft.sakila.Keys.FK_STAFF_ADDRESS, gudusoft.sakila.Keys.FK_STAFF_STORE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public gudusoft.sakila.tables.Staff as(java.lang.String alias) {
		return new gudusoft.sakila.tables.Staff(alias);
	}
}
