/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>sakila</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<gudusoft.sakila.tables.records.ActorRecord, org.jooq.types.UShort> IDENTITY_ACTOR = Identities0.IDENTITY_ACTOR;
	public static final org.jooq.Identity<gudusoft.sakila.tables.records.AddressRecord, org.jooq.types.UShort> IDENTITY_ADDRESS = Identities0.IDENTITY_ADDRESS;
	public static final org.jooq.Identity<gudusoft.sakila.tables.records.CategoryRecord, org.jooq.types.UByte> IDENTITY_CATEGORY = Identities0.IDENTITY_CATEGORY;
	public static final org.jooq.Identity<gudusoft.sakila.tables.records.CityRecord, org.jooq.types.UShort> IDENTITY_CITY = Identities0.IDENTITY_CITY;
	public static final org.jooq.Identity<gudusoft.sakila.tables.records.CountryRecord, org.jooq.types.UShort> IDENTITY_COUNTRY = Identities0.IDENTITY_COUNTRY;
	public static final org.jooq.Identity<gudusoft.sakila.tables.records.CustomerRecord, org.jooq.types.UShort> IDENTITY_CUSTOMER = Identities0.IDENTITY_CUSTOMER;
	public static final org.jooq.Identity<gudusoft.sakila.tables.records.FilmRecord, org.jooq.types.UShort> IDENTITY_FILM = Identities0.IDENTITY_FILM;
	public static final org.jooq.Identity<gudusoft.sakila.tables.records.InventoryRecord, org.jooq.types.UInteger> IDENTITY_INVENTORY = Identities0.IDENTITY_INVENTORY;
	public static final org.jooq.Identity<gudusoft.sakila.tables.records.LanguageRecord, org.jooq.types.UByte> IDENTITY_LANGUAGE = Identities0.IDENTITY_LANGUAGE;
	public static final org.jooq.Identity<gudusoft.sakila.tables.records.PaymentRecord, org.jooq.types.UShort> IDENTITY_PAYMENT = Identities0.IDENTITY_PAYMENT;
	public static final org.jooq.Identity<gudusoft.sakila.tables.records.RentalRecord, java.lang.Integer> IDENTITY_RENTAL = Identities0.IDENTITY_RENTAL;
	public static final org.jooq.Identity<gudusoft.sakila.tables.records.StaffRecord, org.jooq.types.UByte> IDENTITY_STAFF = Identities0.IDENTITY_STAFF;
	public static final org.jooq.Identity<gudusoft.sakila.tables.records.StoreRecord, org.jooq.types.UByte> IDENTITY_STORE = Identities0.IDENTITY_STORE;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.ActorRecord> KEY_ACTOR_PRIMARY = UniqueKeys0.KEY_ACTOR_PRIMARY;
	public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.AddressRecord> KEY_ADDRESS_PRIMARY = UniqueKeys0.KEY_ADDRESS_PRIMARY;
	public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.CategoryRecord> KEY_CATEGORY_PRIMARY = UniqueKeys0.KEY_CATEGORY_PRIMARY;
	public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.CityRecord> KEY_CITY_PRIMARY = UniqueKeys0.KEY_CITY_PRIMARY;
	public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.CountryRecord> KEY_COUNTRY_PRIMARY = UniqueKeys0.KEY_COUNTRY_PRIMARY;
	public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.CustomerRecord> KEY_CUSTOMER_PRIMARY = UniqueKeys0.KEY_CUSTOMER_PRIMARY;
	public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.FilmRecord> KEY_FILM_PRIMARY = UniqueKeys0.KEY_FILM_PRIMARY;
	public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.FilmActorRecord> KEY_FILM_ACTOR_PRIMARY = UniqueKeys0.KEY_FILM_ACTOR_PRIMARY;
	public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.FilmCategoryRecord> KEY_FILM_CATEGORY_PRIMARY = UniqueKeys0.KEY_FILM_CATEGORY_PRIMARY;
	public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.FilmTextRecord> KEY_FILM_TEXT_PRIMARY = UniqueKeys0.KEY_FILM_TEXT_PRIMARY;
	public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.InventoryRecord> KEY_INVENTORY_PRIMARY = UniqueKeys0.KEY_INVENTORY_PRIMARY;
	public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.LanguageRecord> KEY_LANGUAGE_PRIMARY = UniqueKeys0.KEY_LANGUAGE_PRIMARY;
	public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.PaymentRecord> KEY_PAYMENT_PRIMARY = UniqueKeys0.KEY_PAYMENT_PRIMARY;
	public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.RentalRecord> KEY_RENTAL_PRIMARY = UniqueKeys0.KEY_RENTAL_PRIMARY;
	public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.RentalRecord> KEY_RENTAL_RENTAL_DATE = UniqueKeys0.KEY_RENTAL_RENTAL_DATE;
	public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.StaffRecord> KEY_STAFF_PRIMARY = UniqueKeys0.KEY_STAFF_PRIMARY;
	public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.StoreRecord> KEY_STORE_PRIMARY = UniqueKeys0.KEY_STORE_PRIMARY;
	public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.StoreRecord> KEY_STORE_IDX_UNIQUE_MANAGER = UniqueKeys0.KEY_STORE_IDX_UNIQUE_MANAGER;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.AddressRecord, gudusoft.sakila.tables.records.CityRecord> FK_ADDRESS_CITY = ForeignKeys0.FK_ADDRESS_CITY;
	public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.CityRecord, gudusoft.sakila.tables.records.CountryRecord> FK_CITY_COUNTRY = ForeignKeys0.FK_CITY_COUNTRY;
	public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.CustomerRecord, gudusoft.sakila.tables.records.StoreRecord> FK_CUSTOMER_STORE = ForeignKeys0.FK_CUSTOMER_STORE;
	public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.CustomerRecord, gudusoft.sakila.tables.records.AddressRecord> FK_CUSTOMER_ADDRESS = ForeignKeys0.FK_CUSTOMER_ADDRESS;
	public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.FilmRecord, gudusoft.sakila.tables.records.LanguageRecord> FK_FILM_LANGUAGE = ForeignKeys0.FK_FILM_LANGUAGE;
	public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.FilmRecord, gudusoft.sakila.tables.records.LanguageRecord> FK_FILM_LANGUAGE_ORIGINAL = ForeignKeys0.FK_FILM_LANGUAGE_ORIGINAL;
	public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.FilmActorRecord, gudusoft.sakila.tables.records.ActorRecord> FK_FILM_ACTOR_ACTOR = ForeignKeys0.FK_FILM_ACTOR_ACTOR;
	public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.FilmActorRecord, gudusoft.sakila.tables.records.FilmRecord> FK_FILM_ACTOR_FILM = ForeignKeys0.FK_FILM_ACTOR_FILM;
	public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.FilmCategoryRecord, gudusoft.sakila.tables.records.FilmRecord> FK_FILM_CATEGORY_FILM = ForeignKeys0.FK_FILM_CATEGORY_FILM;
	public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.FilmCategoryRecord, gudusoft.sakila.tables.records.CategoryRecord> FK_FILM_CATEGORY_CATEGORY = ForeignKeys0.FK_FILM_CATEGORY_CATEGORY;
	public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.InventoryRecord, gudusoft.sakila.tables.records.FilmRecord> FK_INVENTORY_FILM = ForeignKeys0.FK_INVENTORY_FILM;
	public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.InventoryRecord, gudusoft.sakila.tables.records.StoreRecord> FK_INVENTORY_STORE = ForeignKeys0.FK_INVENTORY_STORE;
	public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.PaymentRecord, gudusoft.sakila.tables.records.CustomerRecord> FK_PAYMENT_CUSTOMER = ForeignKeys0.FK_PAYMENT_CUSTOMER;
	public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.PaymentRecord, gudusoft.sakila.tables.records.StaffRecord> FK_PAYMENT_STAFF = ForeignKeys0.FK_PAYMENT_STAFF;
	public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.PaymentRecord, gudusoft.sakila.tables.records.RentalRecord> FK_PAYMENT_RENTAL = ForeignKeys0.FK_PAYMENT_RENTAL;
	public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.RentalRecord, gudusoft.sakila.tables.records.InventoryRecord> FK_RENTAL_INVENTORY = ForeignKeys0.FK_RENTAL_INVENTORY;
	public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.RentalRecord, gudusoft.sakila.tables.records.CustomerRecord> FK_RENTAL_CUSTOMER = ForeignKeys0.FK_RENTAL_CUSTOMER;
	public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.RentalRecord, gudusoft.sakila.tables.records.StaffRecord> FK_RENTAL_STAFF = ForeignKeys0.FK_RENTAL_STAFF;
	public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.StaffRecord, gudusoft.sakila.tables.records.AddressRecord> FK_STAFF_ADDRESS = ForeignKeys0.FK_STAFF_ADDRESS;
	public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.StaffRecord, gudusoft.sakila.tables.records.StoreRecord> FK_STAFF_STORE = ForeignKeys0.FK_STAFF_STORE;
	public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.StoreRecord, gudusoft.sakila.tables.records.StaffRecord> FK_STORE_STAFF = ForeignKeys0.FK_STORE_STAFF;
	public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.StoreRecord, gudusoft.sakila.tables.records.AddressRecord> FK_STORE_ADDRESS = ForeignKeys0.FK_STORE_ADDRESS;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<gudusoft.sakila.tables.records.ActorRecord, org.jooq.types.UShort> IDENTITY_ACTOR = createIdentity(gudusoft.sakila.tables.Actor.ACTOR, gudusoft.sakila.tables.Actor.ACTOR.ACTOR_ID);
		public static org.jooq.Identity<gudusoft.sakila.tables.records.AddressRecord, org.jooq.types.UShort> IDENTITY_ADDRESS = createIdentity(gudusoft.sakila.tables.Address.ADDRESS, gudusoft.sakila.tables.Address.ADDRESS.ADDRESS_ID);
		public static org.jooq.Identity<gudusoft.sakila.tables.records.CategoryRecord, org.jooq.types.UByte> IDENTITY_CATEGORY = createIdentity(gudusoft.sakila.tables.Category.CATEGORY, gudusoft.sakila.tables.Category.CATEGORY.CATEGORY_ID);
		public static org.jooq.Identity<gudusoft.sakila.tables.records.CityRecord, org.jooq.types.UShort> IDENTITY_CITY = createIdentity(gudusoft.sakila.tables.City.CITY, gudusoft.sakila.tables.City.CITY.CITY_ID);
		public static org.jooq.Identity<gudusoft.sakila.tables.records.CountryRecord, org.jooq.types.UShort> IDENTITY_COUNTRY = createIdentity(gudusoft.sakila.tables.Country.COUNTRY, gudusoft.sakila.tables.Country.COUNTRY.COUNTRY_ID);
		public static org.jooq.Identity<gudusoft.sakila.tables.records.CustomerRecord, org.jooq.types.UShort> IDENTITY_CUSTOMER = createIdentity(gudusoft.sakila.tables.Customer.CUSTOMER, gudusoft.sakila.tables.Customer.CUSTOMER.CUSTOMER_ID);
		public static org.jooq.Identity<gudusoft.sakila.tables.records.FilmRecord, org.jooq.types.UShort> IDENTITY_FILM = createIdentity(gudusoft.sakila.tables.Film.FILM, gudusoft.sakila.tables.Film.FILM.FILM_ID);
		public static org.jooq.Identity<gudusoft.sakila.tables.records.InventoryRecord, org.jooq.types.UInteger> IDENTITY_INVENTORY = createIdentity(gudusoft.sakila.tables.Inventory.INVENTORY, gudusoft.sakila.tables.Inventory.INVENTORY.INVENTORY_ID);
		public static org.jooq.Identity<gudusoft.sakila.tables.records.LanguageRecord, org.jooq.types.UByte> IDENTITY_LANGUAGE = createIdentity(gudusoft.sakila.tables.Language.LANGUAGE, gudusoft.sakila.tables.Language.LANGUAGE.LANGUAGE_ID);
		public static org.jooq.Identity<gudusoft.sakila.tables.records.PaymentRecord, org.jooq.types.UShort> IDENTITY_PAYMENT = createIdentity(gudusoft.sakila.tables.Payment.PAYMENT, gudusoft.sakila.tables.Payment.PAYMENT.PAYMENT_ID);
		public static org.jooq.Identity<gudusoft.sakila.tables.records.RentalRecord, java.lang.Integer> IDENTITY_RENTAL = createIdentity(gudusoft.sakila.tables.Rental.RENTAL, gudusoft.sakila.tables.Rental.RENTAL.RENTAL_ID);
		public static org.jooq.Identity<gudusoft.sakila.tables.records.StaffRecord, org.jooq.types.UByte> IDENTITY_STAFF = createIdentity(gudusoft.sakila.tables.Staff.STAFF, gudusoft.sakila.tables.Staff.STAFF.STAFF_ID);
		public static org.jooq.Identity<gudusoft.sakila.tables.records.StoreRecord, org.jooq.types.UByte> IDENTITY_STORE = createIdentity(gudusoft.sakila.tables.Store.STORE, gudusoft.sakila.tables.Store.STORE.STORE_ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.ActorRecord> KEY_ACTOR_PRIMARY = createUniqueKey(gudusoft.sakila.tables.Actor.ACTOR, gudusoft.sakila.tables.Actor.ACTOR.ACTOR_ID);
		public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.AddressRecord> KEY_ADDRESS_PRIMARY = createUniqueKey(gudusoft.sakila.tables.Address.ADDRESS, gudusoft.sakila.tables.Address.ADDRESS.ADDRESS_ID);
		public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.CategoryRecord> KEY_CATEGORY_PRIMARY = createUniqueKey(gudusoft.sakila.tables.Category.CATEGORY, gudusoft.sakila.tables.Category.CATEGORY.CATEGORY_ID);
		public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.CityRecord> KEY_CITY_PRIMARY = createUniqueKey(gudusoft.sakila.tables.City.CITY, gudusoft.sakila.tables.City.CITY.CITY_ID);
		public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.CountryRecord> KEY_COUNTRY_PRIMARY = createUniqueKey(gudusoft.sakila.tables.Country.COUNTRY, gudusoft.sakila.tables.Country.COUNTRY.COUNTRY_ID);
		public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.CustomerRecord> KEY_CUSTOMER_PRIMARY = createUniqueKey(gudusoft.sakila.tables.Customer.CUSTOMER, gudusoft.sakila.tables.Customer.CUSTOMER.CUSTOMER_ID);
		public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.FilmRecord> KEY_FILM_PRIMARY = createUniqueKey(gudusoft.sakila.tables.Film.FILM, gudusoft.sakila.tables.Film.FILM.FILM_ID);
		public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.FilmActorRecord> KEY_FILM_ACTOR_PRIMARY = createUniqueKey(gudusoft.sakila.tables.FilmActor.FILM_ACTOR, gudusoft.sakila.tables.FilmActor.FILM_ACTOR.ACTOR_ID, gudusoft.sakila.tables.FilmActor.FILM_ACTOR.FILM_ID);
		public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.FilmCategoryRecord> KEY_FILM_CATEGORY_PRIMARY = createUniqueKey(gudusoft.sakila.tables.FilmCategory.FILM_CATEGORY, gudusoft.sakila.tables.FilmCategory.FILM_CATEGORY.FILM_ID, gudusoft.sakila.tables.FilmCategory.FILM_CATEGORY.CATEGORY_ID);
		public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.FilmTextRecord> KEY_FILM_TEXT_PRIMARY = createUniqueKey(gudusoft.sakila.tables.FilmText.FILM_TEXT, gudusoft.sakila.tables.FilmText.FILM_TEXT.FILM_ID);
		public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.InventoryRecord> KEY_INVENTORY_PRIMARY = createUniqueKey(gudusoft.sakila.tables.Inventory.INVENTORY, gudusoft.sakila.tables.Inventory.INVENTORY.INVENTORY_ID);
		public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.LanguageRecord> KEY_LANGUAGE_PRIMARY = createUniqueKey(gudusoft.sakila.tables.Language.LANGUAGE, gudusoft.sakila.tables.Language.LANGUAGE.LANGUAGE_ID);
		public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.PaymentRecord> KEY_PAYMENT_PRIMARY = createUniqueKey(gudusoft.sakila.tables.Payment.PAYMENT, gudusoft.sakila.tables.Payment.PAYMENT.PAYMENT_ID);
		public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.RentalRecord> KEY_RENTAL_PRIMARY = createUniqueKey(gudusoft.sakila.tables.Rental.RENTAL, gudusoft.sakila.tables.Rental.RENTAL.RENTAL_ID);
		public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.RentalRecord> KEY_RENTAL_RENTAL_DATE = createUniqueKey(gudusoft.sakila.tables.Rental.RENTAL, gudusoft.sakila.tables.Rental.RENTAL.RENTAL_DATE, gudusoft.sakila.tables.Rental.RENTAL.INVENTORY_ID, gudusoft.sakila.tables.Rental.RENTAL.CUSTOMER_ID);
		public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.StaffRecord> KEY_STAFF_PRIMARY = createUniqueKey(gudusoft.sakila.tables.Staff.STAFF, gudusoft.sakila.tables.Staff.STAFF.STAFF_ID);
		public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.StoreRecord> KEY_STORE_PRIMARY = createUniqueKey(gudusoft.sakila.tables.Store.STORE, gudusoft.sakila.tables.Store.STORE.STORE_ID);
		public static final org.jooq.UniqueKey<gudusoft.sakila.tables.records.StoreRecord> KEY_STORE_IDX_UNIQUE_MANAGER = createUniqueKey(gudusoft.sakila.tables.Store.STORE, gudusoft.sakila.tables.Store.STORE.MANAGER_STAFF_ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.AddressRecord, gudusoft.sakila.tables.records.CityRecord> FK_ADDRESS_CITY = createForeignKey(gudusoft.sakila.Keys.KEY_CITY_PRIMARY, gudusoft.sakila.tables.Address.ADDRESS, gudusoft.sakila.tables.Address.ADDRESS.CITY_ID);
		public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.CityRecord, gudusoft.sakila.tables.records.CountryRecord> FK_CITY_COUNTRY = createForeignKey(gudusoft.sakila.Keys.KEY_COUNTRY_PRIMARY, gudusoft.sakila.tables.City.CITY, gudusoft.sakila.tables.City.CITY.COUNTRY_ID);
		public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.CustomerRecord, gudusoft.sakila.tables.records.StoreRecord> FK_CUSTOMER_STORE = createForeignKey(gudusoft.sakila.Keys.KEY_STORE_PRIMARY, gudusoft.sakila.tables.Customer.CUSTOMER, gudusoft.sakila.tables.Customer.CUSTOMER.STORE_ID);
		public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.CustomerRecord, gudusoft.sakila.tables.records.AddressRecord> FK_CUSTOMER_ADDRESS = createForeignKey(gudusoft.sakila.Keys.KEY_ADDRESS_PRIMARY, gudusoft.sakila.tables.Customer.CUSTOMER, gudusoft.sakila.tables.Customer.CUSTOMER.ADDRESS_ID);
		public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.FilmRecord, gudusoft.sakila.tables.records.LanguageRecord> FK_FILM_LANGUAGE = createForeignKey(gudusoft.sakila.Keys.KEY_LANGUAGE_PRIMARY, gudusoft.sakila.tables.Film.FILM, gudusoft.sakila.tables.Film.FILM.LANGUAGE_ID);
		public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.FilmRecord, gudusoft.sakila.tables.records.LanguageRecord> FK_FILM_LANGUAGE_ORIGINAL = createForeignKey(gudusoft.sakila.Keys.KEY_LANGUAGE_PRIMARY, gudusoft.sakila.tables.Film.FILM, gudusoft.sakila.tables.Film.FILM.ORIGINAL_LANGUAGE_ID);
		public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.FilmActorRecord, gudusoft.sakila.tables.records.ActorRecord> FK_FILM_ACTOR_ACTOR = createForeignKey(gudusoft.sakila.Keys.KEY_ACTOR_PRIMARY, gudusoft.sakila.tables.FilmActor.FILM_ACTOR, gudusoft.sakila.tables.FilmActor.FILM_ACTOR.ACTOR_ID);
		public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.FilmActorRecord, gudusoft.sakila.tables.records.FilmRecord> FK_FILM_ACTOR_FILM = createForeignKey(gudusoft.sakila.Keys.KEY_FILM_PRIMARY, gudusoft.sakila.tables.FilmActor.FILM_ACTOR, gudusoft.sakila.tables.FilmActor.FILM_ACTOR.FILM_ID);
		public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.FilmCategoryRecord, gudusoft.sakila.tables.records.FilmRecord> FK_FILM_CATEGORY_FILM = createForeignKey(gudusoft.sakila.Keys.KEY_FILM_PRIMARY, gudusoft.sakila.tables.FilmCategory.FILM_CATEGORY, gudusoft.sakila.tables.FilmCategory.FILM_CATEGORY.FILM_ID);
		public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.FilmCategoryRecord, gudusoft.sakila.tables.records.CategoryRecord> FK_FILM_CATEGORY_CATEGORY = createForeignKey(gudusoft.sakila.Keys.KEY_CATEGORY_PRIMARY, gudusoft.sakila.tables.FilmCategory.FILM_CATEGORY, gudusoft.sakila.tables.FilmCategory.FILM_CATEGORY.CATEGORY_ID);
		public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.InventoryRecord, gudusoft.sakila.tables.records.FilmRecord> FK_INVENTORY_FILM = createForeignKey(gudusoft.sakila.Keys.KEY_FILM_PRIMARY, gudusoft.sakila.tables.Inventory.INVENTORY, gudusoft.sakila.tables.Inventory.INVENTORY.FILM_ID);
		public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.InventoryRecord, gudusoft.sakila.tables.records.StoreRecord> FK_INVENTORY_STORE = createForeignKey(gudusoft.sakila.Keys.KEY_STORE_PRIMARY, gudusoft.sakila.tables.Inventory.INVENTORY, gudusoft.sakila.tables.Inventory.INVENTORY.STORE_ID);
		public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.PaymentRecord, gudusoft.sakila.tables.records.CustomerRecord> FK_PAYMENT_CUSTOMER = createForeignKey(gudusoft.sakila.Keys.KEY_CUSTOMER_PRIMARY, gudusoft.sakila.tables.Payment.PAYMENT, gudusoft.sakila.tables.Payment.PAYMENT.CUSTOMER_ID);
		public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.PaymentRecord, gudusoft.sakila.tables.records.StaffRecord> FK_PAYMENT_STAFF = createForeignKey(gudusoft.sakila.Keys.KEY_STAFF_PRIMARY, gudusoft.sakila.tables.Payment.PAYMENT, gudusoft.sakila.tables.Payment.PAYMENT.STAFF_ID);
		public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.PaymentRecord, gudusoft.sakila.tables.records.RentalRecord> FK_PAYMENT_RENTAL = createForeignKey(gudusoft.sakila.Keys.KEY_RENTAL_PRIMARY, gudusoft.sakila.tables.Payment.PAYMENT, gudusoft.sakila.tables.Payment.PAYMENT.RENTAL_ID);
		public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.RentalRecord, gudusoft.sakila.tables.records.InventoryRecord> FK_RENTAL_INVENTORY = createForeignKey(gudusoft.sakila.Keys.KEY_INVENTORY_PRIMARY, gudusoft.sakila.tables.Rental.RENTAL, gudusoft.sakila.tables.Rental.RENTAL.INVENTORY_ID);
		public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.RentalRecord, gudusoft.sakila.tables.records.CustomerRecord> FK_RENTAL_CUSTOMER = createForeignKey(gudusoft.sakila.Keys.KEY_CUSTOMER_PRIMARY, gudusoft.sakila.tables.Rental.RENTAL, gudusoft.sakila.tables.Rental.RENTAL.CUSTOMER_ID);
		public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.RentalRecord, gudusoft.sakila.tables.records.StaffRecord> FK_RENTAL_STAFF = createForeignKey(gudusoft.sakila.Keys.KEY_STAFF_PRIMARY, gudusoft.sakila.tables.Rental.RENTAL, gudusoft.sakila.tables.Rental.RENTAL.STAFF_ID);
		public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.StaffRecord, gudusoft.sakila.tables.records.AddressRecord> FK_STAFF_ADDRESS = createForeignKey(gudusoft.sakila.Keys.KEY_ADDRESS_PRIMARY, gudusoft.sakila.tables.Staff.STAFF, gudusoft.sakila.tables.Staff.STAFF.ADDRESS_ID);
		public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.StaffRecord, gudusoft.sakila.tables.records.StoreRecord> FK_STAFF_STORE = createForeignKey(gudusoft.sakila.Keys.KEY_STORE_PRIMARY, gudusoft.sakila.tables.Staff.STAFF, gudusoft.sakila.tables.Staff.STAFF.STORE_ID);
		public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.StoreRecord, gudusoft.sakila.tables.records.StaffRecord> FK_STORE_STAFF = createForeignKey(gudusoft.sakila.Keys.KEY_STAFF_PRIMARY, gudusoft.sakila.tables.Store.STORE, gudusoft.sakila.tables.Store.STORE.MANAGER_STAFF_ID);
		public static final org.jooq.ForeignKey<gudusoft.sakila.tables.records.StoreRecord, gudusoft.sakila.tables.records.AddressRecord> FK_STORE_ADDRESS = createForeignKey(gudusoft.sakila.Keys.KEY_ADDRESS_PRIMARY, gudusoft.sakila.tables.Store.STORE, gudusoft.sakila.tables.Store.STORE.ADDRESS_ID);
	}
}
