/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sakila extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1839348543;

	/**
	 * The singleton instance of <code>sakila</code>
	 */
	public static final Sakila SAKILA = new Sakila();

	/**
	 * No further instances allowed
	 */
	private Sakila() {
		super("sakila");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			gudusoft.sakila.tables.Actor.ACTOR,
			gudusoft.sakila.tables.ActorInfo.ACTOR_INFO,
			gudusoft.sakila.tables.Address.ADDRESS,
			gudusoft.sakila.tables.Category.CATEGORY,
			gudusoft.sakila.tables.City.CITY,
			gudusoft.sakila.tables.Country.COUNTRY,
			gudusoft.sakila.tables.Customer.CUSTOMER,
			gudusoft.sakila.tables.CustomerList.CUSTOMER_LIST,
			gudusoft.sakila.tables.Film.FILM,
			gudusoft.sakila.tables.FilmActor.FILM_ACTOR,
			gudusoft.sakila.tables.FilmCategory.FILM_CATEGORY,
			gudusoft.sakila.tables.FilmList.FILM_LIST,
			gudusoft.sakila.tables.FilmText.FILM_TEXT,
			gudusoft.sakila.tables.Inventory.INVENTORY,
			gudusoft.sakila.tables.Language.LANGUAGE,
			gudusoft.sakila.tables.NicerButSlowerFilmList.NICER_BUT_SLOWER_FILM_LIST,
			gudusoft.sakila.tables.Payment.PAYMENT,
			gudusoft.sakila.tables.Rental.RENTAL,
			gudusoft.sakila.tables.SalesByFilmCategory.SALES_BY_FILM_CATEGORY,
			gudusoft.sakila.tables.SalesByStore.SALES_BY_STORE,
			gudusoft.sakila.tables.Staff.STAFF,
			gudusoft.sakila.tables.StaffList.STAFF_LIST,
			gudusoft.sakila.tables.Store.STORE);
	}
}
