/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in sakila
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table sakila.actor
	 */
	public static final gudusoft.sakila.tables.Actor ACTOR = gudusoft.sakila.tables.Actor.ACTOR;

	/**
	 * VIEW
	 */
	public static final gudusoft.sakila.tables.ActorInfo ACTOR_INFO = gudusoft.sakila.tables.ActorInfo.ACTOR_INFO;

	/**
	 * The table sakila.address
	 */
	public static final gudusoft.sakila.tables.Address ADDRESS = gudusoft.sakila.tables.Address.ADDRESS;

	/**
	 * The table sakila.category
	 */
	public static final gudusoft.sakila.tables.Category CATEGORY = gudusoft.sakila.tables.Category.CATEGORY;

	/**
	 * The table sakila.city
	 */
	public static final gudusoft.sakila.tables.City CITY = gudusoft.sakila.tables.City.CITY;

	/**
	 * The table sakila.country
	 */
	public static final gudusoft.sakila.tables.Country COUNTRY = gudusoft.sakila.tables.Country.COUNTRY;

	/**
	 * The table sakila.customer
	 */
	public static final gudusoft.sakila.tables.Customer CUSTOMER = gudusoft.sakila.tables.Customer.CUSTOMER;

	/**
	 * VIEW
	 */
	public static final gudusoft.sakila.tables.CustomerList CUSTOMER_LIST = gudusoft.sakila.tables.CustomerList.CUSTOMER_LIST;

	/**
	 * The table sakila.film
	 */
	public static final gudusoft.sakila.tables.Film FILM = gudusoft.sakila.tables.Film.FILM;

	/**
	 * The table sakila.film_actor
	 */
	public static final gudusoft.sakila.tables.FilmActor FILM_ACTOR = gudusoft.sakila.tables.FilmActor.FILM_ACTOR;

	/**
	 * The table sakila.film_category
	 */
	public static final gudusoft.sakila.tables.FilmCategory FILM_CATEGORY = gudusoft.sakila.tables.FilmCategory.FILM_CATEGORY;

	/**
	 * VIEW
	 */
	public static final gudusoft.sakila.tables.FilmList FILM_LIST = gudusoft.sakila.tables.FilmList.FILM_LIST;

	/**
	 * The table sakila.film_text
	 */
	public static final gudusoft.sakila.tables.FilmText FILM_TEXT = gudusoft.sakila.tables.FilmText.FILM_TEXT;

	/**
	 * The table sakila.inventory
	 */
	public static final gudusoft.sakila.tables.Inventory INVENTORY = gudusoft.sakila.tables.Inventory.INVENTORY;

	/**
	 * The table sakila.language
	 */
	public static final gudusoft.sakila.tables.Language LANGUAGE = gudusoft.sakila.tables.Language.LANGUAGE;

	/**
	 * VIEW
	 */
	public static final gudusoft.sakila.tables.NicerButSlowerFilmList NICER_BUT_SLOWER_FILM_LIST = gudusoft.sakila.tables.NicerButSlowerFilmList.NICER_BUT_SLOWER_FILM_LIST;

	/**
	 * The table sakila.payment
	 */
	public static final gudusoft.sakila.tables.Payment PAYMENT = gudusoft.sakila.tables.Payment.PAYMENT;

	/**
	 * The table sakila.rental
	 */
	public static final gudusoft.sakila.tables.Rental RENTAL = gudusoft.sakila.tables.Rental.RENTAL;

	/**
	 * VIEW
	 */
	public static final gudusoft.sakila.tables.SalesByFilmCategory SALES_BY_FILM_CATEGORY = gudusoft.sakila.tables.SalesByFilmCategory.SALES_BY_FILM_CATEGORY;

	/**
	 * VIEW
	 */
	public static final gudusoft.sakila.tables.SalesByStore SALES_BY_STORE = gudusoft.sakila.tables.SalesByStore.SALES_BY_STORE;

	/**
	 * The table sakila.staff
	 */
	public static final gudusoft.sakila.tables.Staff STAFF = gudusoft.sakila.tables.Staff.STAFF;

	/**
	 * VIEW
	 */
	public static final gudusoft.sakila.tables.StaffList STAFF_LIST = gudusoft.sakila.tables.StaffList.STAFF_LIST;

	/**
	 * The table sakila.store
	 */
	public static final gudusoft.sakila.tables.Store STORE = gudusoft.sakila.tables.Store.STORE;
}
