/**
 * This class is generated by jOOQ
 */
package gudusoft.sakila.routines;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InventoryInStock extends org.jooq.impl.AbstractRoutine<java.lang.Byte> {

	private static final long serialVersionUID = -1026849333;

	/**
	 * The parameter <code>sakila.inventory_in_stock.RETURN_VALUE</code>. 
	 */
	public static final org.jooq.Parameter<java.lang.Byte> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.TINYINT);

	/**
	 * The parameter <code>sakila.inventory_in_stock.p_inventory_id</code>. 
	 */
	public static final org.jooq.Parameter<java.lang.Integer> P_INVENTORY_ID = createParameter("p_inventory_id", org.jooq.impl.SQLDataType.INTEGER);

	/**
	 * Create a new routine call instance
	 */
	public InventoryInStock() {
		super("inventory_in_stock", gudusoft.sakila.Sakila.SAKILA, org.jooq.impl.SQLDataType.TINYINT);

		setReturnParameter(RETURN_VALUE);
		addInParameter(P_INVENTORY_ID);
	}

	/**
	 * Set the <code>p_inventory_id</code> parameter IN value to the routine
	 */
	public void setPInventoryId(java.lang.Integer value) {
		setValue(gudusoft.sakila.routines.InventoryInStock.P_INVENTORY_ID, value);
	}

	/**
	 * Set the <code>p_inventory_id</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setPInventoryId(org.jooq.Field<java.lang.Integer> field) {
		setField(P_INVENTORY_ID, field);
	}
}
