/**
 * This class is generated by jOOQ
 */
package gudusoft.guestbook;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in guestbook
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * InnoDB free: 3072 kB
	 */
	public static final gudusoft.guestbook.tables.Mails MAILS = gudusoft.guestbook.tables.Mails.MAILS;

	/**
	 * InnoDB free: 3072 kB
	 */
	public static final gudusoft.guestbook.tables.Posts POSTS = gudusoft.guestbook.tables.Posts.POSTS;
}
