/**
 * This class is generated by jOOQ
 */
package gudusoft.school.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Student extends org.jooq.impl.TableImpl<gudusoft.school.tables.records.StudentRecord> {

	private static final long serialVersionUID = 1160442299;

	/**
	 * The singleton instance of <code>public.student</code>
	 */
	public static final gudusoft.school.tables.Student STUDENT = new gudusoft.school.tables.Student();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<gudusoft.school.tables.records.StudentRecord> getRecordType() {
		return gudusoft.school.tables.records.StudentRecord.class;
	}

	/**
	 * The column <code>public.student.name</code>. 
	 */
	public final org.jooq.TableField<gudusoft.school.tables.records.StudentRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(20), this);

	/**
	 * The column <code>public.student.age</code>. 
	 */
	public final org.jooq.TableField<gudusoft.school.tables.records.StudentRecord, java.lang.Integer> AGE = createField("age", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>public.student.sex</code>. 
	 */
	public final org.jooq.TableField<gudusoft.school.tables.records.StudentRecord, java.lang.String> SEX = createField("sex", org.jooq.impl.SQLDataType.VARCHAR.length(20), this);

	/**
	 * The column <code>public.student.signupdate</code>. 
	 */
	public final org.jooq.TableField<gudusoft.school.tables.records.StudentRecord, java.sql.Date> SIGNUPDATE = createField("signupdate", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * Create a <code>public.student</code> table reference
	 */
	public Student() {
		super("student", gudusoft.school.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.student</code> table reference
	 */
	public Student(java.lang.String alias) {
		super(alias, gudusoft.school.Public.PUBLIC, gudusoft.school.tables.Student.STUDENT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public gudusoft.school.tables.Student as(java.lang.String alias) {
		return new gudusoft.school.tables.Student(alias);
	}
}
