/**
 * This class is generated by jOOQ
 */
package gudusoft.school;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.student
	 */
	public static final gudusoft.school.tables.Student STUDENT = gudusoft.school.tables.Student.STUDENT;
}
