/**
 * This class is generated by jOOQ
 */
package gudusoft.guestbook.tables;

/**
 * This class is generated by jOOQ.
 *
 * InnoDB free: 3072 kB
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mails extends org.jooq.impl.TableImpl<gudusoft.guestbook.tables.records.MailsRecord> {

	private static final long serialVersionUID = 798021259;

	/**
	 * The singleton instance of <code>guestbook.mails</code>
	 */
	public static final gudusoft.guestbook.tables.Mails MAILS = new gudusoft.guestbook.tables.Mails();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<gudusoft.guestbook.tables.records.MailsRecord> getRecordType() {
		return gudusoft.guestbook.tables.records.MailsRecord.class;
	}

	/**
	 * The column <code>guestbook.mails.id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.guestbook.tables.records.MailsRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>guestbook.mails.address</code>. 
	 */
	public final org.jooq.TableField<gudusoft.guestbook.tables.records.MailsRecord, java.lang.String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>guestbook.mails</code> table reference
	 */
	public Mails() {
		super("mails", gudusoft.guestbook.Guestbook.GUESTBOOK);
	}

	/**
	 * Create an aliased <code>guestbook.mails</code> table reference
	 */
	public Mails(java.lang.String alias) {
		super(alias, gudusoft.guestbook.Guestbook.GUESTBOOK, gudusoft.guestbook.tables.Mails.MAILS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public gudusoft.guestbook.tables.Mails as(java.lang.String alias) {
		return new gudusoft.guestbook.tables.Mails(alias);
	}
}
