/**
 * This class is generated by jOOQ
 */
package gudusoft.guestbook.tables;

/**
 * This class is generated by jOOQ.
 *
 * InnoDB free: 3072 kB
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Posts extends org.jooq.impl.TableImpl<gudusoft.guestbook.tables.records.PostsRecord> {

	private static final long serialVersionUID = -443390131;

	/**
	 * The singleton instance of <code>guestbook.posts</code>
	 */
	public static final gudusoft.guestbook.tables.Posts POSTS = new gudusoft.guestbook.tables.Posts();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<gudusoft.guestbook.tables.records.PostsRecord> getRecordType() {
		return gudusoft.guestbook.tables.records.PostsRecord.class;
	}

	/**
	 * The column <code>guestbook.posts.id</code>. 
	 */
	public final org.jooq.TableField<gudusoft.guestbook.tables.records.PostsRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>guestbook.posts.body</code>. 
	 */
	public final org.jooq.TableField<gudusoft.guestbook.tables.records.PostsRecord, java.lang.String> BODY = createField("body", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>guestbook.posts.timestamp</code>. 
	 */
	public final org.jooq.TableField<gudusoft.guestbook.tables.records.PostsRecord, java.sql.Timestamp> TIMESTAMP = createField("timestamp", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>guestbook.posts.title</code>. 
	 */
	public final org.jooq.TableField<gudusoft.guestbook.tables.records.PostsRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>guestbook.posts</code> table reference
	 */
	public Posts() {
		super("posts", gudusoft.guestbook.Guestbook.GUESTBOOK);
	}

	/**
	 * Create an aliased <code>guestbook.posts</code> table reference
	 */
	public Posts(java.lang.String alias) {
		super(alias, gudusoft.guestbook.Guestbook.GUESTBOOK, gudusoft.guestbook.tables.Posts.POSTS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public gudusoft.guestbook.tables.Posts as(java.lang.String alias) {
		return new gudusoft.guestbook.tables.Posts(alias);
	}
}
