/**
 * This class is generated by jOOQ
 */
package gudusoft.school.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentRecord extends org.jooq.impl.TableRecordImpl<gudusoft.school.tables.records.StudentRecord> implements org.jooq.Record4<java.lang.String, java.lang.Integer, java.lang.String, java.sql.Date> {

	private static final long serialVersionUID = 2069015602;

	/**
	 * Setter for <code>public.student.name</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.student.name</code>. 
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.student.age</code>. 
	 */
	public void setAge(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.student.age</code>. 
	 */
	public java.lang.Integer getAge() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.student.sex</code>. 
	 */
	public void setSex(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.student.sex</code>. 
	 */
	public java.lang.String getSex() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.student.signupdate</code>. 
	 */
	public void setSignupdate(java.sql.Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.student.signupdate</code>. 
	 */
	public java.sql.Date getSignupdate() {
		return (java.sql.Date) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.Integer, java.lang.String, java.sql.Date> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.Integer, java.lang.String, java.sql.Date> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return gudusoft.school.tables.Student.STUDENT.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return gudusoft.school.tables.Student.STUDENT.AGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return gudusoft.school.tables.Student.STUDENT.SEX;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field4() {
		return gudusoft.school.tables.Student.STUDENT.SIGNUPDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getAge();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getSex();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value4() {
		return getSignupdate();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StudentRecord
	 */
	public StudentRecord() {
		super(gudusoft.school.tables.Student.STUDENT);
	}
}
